services:
  app:
    image: reactive_food
    ports:
      - 8080:80
    #command: ["php bin/console server:run"]
    volumes:
      - ./:/var/www/html
      - ./docker/logs:/var/log/apache2
      - ./docker/php.ini:/etc/php/8.3/apache2/php.ini
      - ./docker/000-default.conf:/etc/apache2/sites-available/000-default.conf
#      - ./docker/xdebug.ini:/etc/php/8.3/apache2/conf.d/20-xdebug.ini
    links:
      - db:mysql

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: base
      MYSQL_USER: kdev
      MYSQL_PASSWORD: 132456
    ports:
      - "3306:3306"
    volumes:
      - ./docker/data:/var/lib/mysql
            
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  db_data: